version: '3.8'
services:
  dhis2gateway:
    image: dhis2gateway:latest
    ports:
      - 3000:3000
    restart: always
    environment:
      GTW_DB_HOST: localhost
      GTW_DB_PORT: 5432
      GTW_DB_NAME: api_gateway
      GTW_DB_USER: dhis
      GTW_DB_PASS: dhis
      WHD_DB_HOST: localhost
      WHD_DB_PORT: 5432
      WHD_DB_NAME: api_gateway
      WHD_DB_USER: dhis
      WHD_DB_PASS: dhis
      MDD_DB_HOST: localhost
      MDD_DB_PORT: 5432
      MDD_DB_NAME: api_gateway
      MDD_DB_USER: dhis
      MDD_DB_PASS: dhis
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: api_gateway
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
